### ISSUE TITLE
stories.json has been moved to index.json

### ISSUE THREAD

**Issue by JeanBarriere** [LambdaTest/smartui-storybook#79]
Hi,

I'm having an issue implementing smartui-storybook with `storybook@8`.

storybook renamed the `stories.json` file to `index.json` in version 7.
This change prevents smartui to run against any storybook version above 6.X

Read more here: https://storybook.js.org/docs/writing-tests/test-runner#indexjson-mode

**Comment by parthlambdatest** [comment]
@JeanBarriere this issue has been incorporated in the latest release.
Thank you for reporting this issue.

**Comment by JeanBarriere** [comment]
Thanks, working as expected!
